<?php
    /**
     * Created by PhpStorm.
     * User: tengjufeng
     * Date: 2018/12/26
     * Time: 4:40 PM
     */

    namespace app\common\exception;

    use app\common\responseMsg\ResponseMsg;
    use think\exception\Handle;

    class ApiHandle extends Handle {
        public function render (\Exception $e) {

            // TODO: Change the autogenerated stub
            if (config('app_debug') == true) {
                //return parent::render($e);
            }
            return json(ResponseMsg::error($e->getMessage()), $e->getCode());
        }


    }